# Generated by Django 2.2.27 on 2022-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careerName', models.TextField(blank=True, null=True)),
                ('imagePath', models.TextField(max_length=200)),
            ],
        ),
    ]
