# Generated by Django 2.2.27 on 2022-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_careers'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='careerID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careers',
            name='imagePath',
            field=models.URLField(),
        ),
    ]
