# Generated by Django 3.2.9 on 2022-04-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
    ]
