# Generated by Django 2.2.27 on 2022-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220506_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careerID', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=300)),
                ('funfact', models.CharField(max_length=300)),
                ('q1', models.TextField(blank=True, null=True)),
                ('q2', models.TextField(blank=True, null=True)),
                ('q3', models.TextField(blank=True, null=True)),
                ('q4', models.TextField(blank=True, null=True)),
                ('q5', models.TextField(blank=True, null=True)),
                ('q6', models.TextField(blank=True, null=True)),
                ('q7', models.TextField(blank=True, null=True)),
                ('q8', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='careers',
            name='careerID',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='careers',
            name='careerName',
            field=models.CharField(max_length=300),
        ),
    ]
