# Generated by Django 2.2.27 on 2022-05-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220512_2345'),
        ('api', '0004_auto_20220506_1452'),
    ]

    operations = [
    ]
