# Generated by Django 3.2.9 on 2022-05-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220514_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('tech_skill', models.TextField(max_length=50)),
                ('soft_skill', models.TextField(blank=True, null=True)),
                ('daily_duties', models.TextField(blank=True, null=True)),
                ('similar_jobs', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('growth_rate', models.TextField(blank=True, null=True)),
                ('work_env', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='careers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professionalstory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
