# Generated by Django 3.2.9 on 2022-05-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220514_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeroverview',
            name='careerID',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
