# Generated by Django 2.2.27 on 2022-05-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_careeroverview_tech_skill'),
        ('api', '0007_professionalstory_imagepath'),
    ]

    operations = [
    ]
