# Generated by Django 2.2.27 on 2022-05-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220515_1438'),
        ('api', '0011_auto_20220515_1443'),
    ]

    operations = [
    ]
