# Generated by Django 3.2.9 on 2022-05-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220517_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeroverview',
            name='careerID',
            field=models.CharField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
