# Generated by Django 3.2.9 on 2022-05-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_careeroverview_careerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeroverview',
            name='horn_length',
            field=models.TimeField(default=True),
            preserve_default=False,
        ),
    ]
