# Generated by Django 3.2.9 on 2022-05-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_careeroverview_horn_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careeroverview',
            name='horn_length',
        ),
    ]
