# Generated by Django 3.2.9 on 2022-05-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_careeroverview_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careeroverview',
            name='ordering',
        ),
    ]
